In [1]:
import matplotlib.pyplot as plt 
from matplotlib.pylab import rcParams
import pandas as pd
import scipy.stats as sts
import numpy as np
%matplotlib inline
import seaborn as sns
sns.set(style='darkgrid',font='Arial',font_scale=1.2)
rcParams['figure.figsize'] = 12,8
rcParams['axes.spines.top'] = False
rcParams['axes.spines.right'] = False

In [2]:
df = pd.read_csv('City_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv')

In [3]:
columns = df.columns.to_list()

In [4]:
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2000-01-31,2000-02-29,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
0,6181,0,New York,City,NY,NY,New York-Newark-Jersey City,Queens County,254333.0,256156.0,...,700899.0,704665.0,708478.0,712125.0,717414.0,723186.0,727642.0,731085.0,735397.0,740459.0
1,12447,1,Los Angeles,City,CA,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,246626.0,246869.0,...,904722.0,927073.0,951949.0,967546.0,979004.0,982950.0,988131.0,994614.0,1000393.0,1010506.0
2,39051,2,Houston,City,TX,TX,Houston-The Woodlands-Sugar Land,Harris County,110875.0,110872.0,...,221860.0,226514.0,231600.0,237117.0,241341.0,244987.0,247488.0,250360.0,253371.0,256823.0
3,17426,3,Chicago,City,IL,IL,Chicago-Naperville-Elgin,Cook County,165282.0,165621.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
4,6915,4,San Antonio,City,TX,TX,San Antonio-New Braunfels,Bexar County,116801.0,116985.0,...,240640.0,246663.0,252127.0,257891.0,261748.0,265898.0,269596.0,274350.0,279164.0,283697.0

In [5]:
illinois = df[df['State']=='IL']

In [6]:
cook = illinois[illinois['CountyName']=='Cook County']

In [7]:
cook

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2000-01-31,2000-02-29,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
3,17426,3,Chicago,City,IL,IL,Chicago-Naperville-Elgin,Cook County,165282.0,165621.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
523,44597,532,Cicero,City,IL,IL,Chicago-Naperville-Elgin,Cook County,128972.0,129220.0,...,226907.0,229498.0,232578.0,235283.0,237289.0,238760.0,240861.0,243257.0,245957.0,247645.0
568,50764,577,Arlington Heights,City,IL,IL,Chicago-Naperville-Elgin,Cook County,261429.0,261759.0,...,390213.0,394921.0,400663.0,405699.0,408596.0,411208.0,414526.0,417568.0,420270.0,421782.0
582,33889,592,Schaumburg,City,IL,IL,Chicago-Naperville-Elgin,Cook County,206420.0,206899.0,...,318749.0,322037.0,325884.0,329969.0,332546.0,335233.0,338328.0,341091.0,343829.0,345585.0
618,18025,629,Evanston,City,IL,IL,Chicago-Naperville-Elgin,Cook County,302592.0,302905.0,...,502345.0,509733.0,518375.0,526181.0,532433.0,538210.0,544713.0,550440.0,554475.0,556319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18224,31795,21144,Golf,City,IL,IL,Chicago-Naperville-Elgin,Cook County,511254.0,512519.0,...,812506.0,837445.0,865139.0,879458.0,890257.0,898739.0,909127.0,919617.0,929894.0,935990.0
18315,32054,21258,Hodgkins,City,IL,IL,Chicago-Naperville-Elgin,Cook County,146250.0,144877.0,...,289536.0,292275.0,296267.0,299403.0,302809.0,304813.0,307362.0,308740.0,310763.0,311582.0
18597,53214,21606,McCook,City,IL,IL,Chicago-Naperville-Elgin,Cook County,164992.0,162667.0,...,279015.0,282892.0,288192.0,293391.0,297558.0,301130.0,304551.0,307136.0,309673.0,310853.0
19046,31594,22198,Forestview,City,IL,IL,Chicago-Naperville-Elgin,Cook County,164312.0,163407.0,...,236070.0,240865.0,245925.0,249961.0,252382.0,254337.0,256295.0,259127.0,261888.0,264583.0
25781,11693,30967,Great Lakes,City,IL,IL,Chicago-Naperville-Elgin,Cook County,NaN,NaN,...,177033.0,183722.0,190429.0,194787.0,197091.0,190167.0,181762.0,175064.0,176039.0,179851.0

In [8]:
cook = cook.drop(columns=['CountyName', 'Metro', 'State', "StateName",'RegionType'],axis=1)

In [9]:
cook = cook.reset_index()

In [10]:
cook = cook.drop(columns=['index'],axis=1)

In [11]:
cook

,RegionID,SizeRank,RegionName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
0,17426,3,Chicago,165282.0,165621.0,166381.0,167702.0,169196.0,170566.0,172001.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
1,44597,532,Cicero,128972.0,129220.0,129706.0,130518.0,131517.0,132603.0,133856.0,...,226907.0,229498.0,232578.0,235283.0,237289.0,238760.0,240861.0,243257.0,245957.0,247645.0
2,50764,577,Arlington Heights,261429.0,261759.0,262735.0,264406.0,266390.0,267808.0,269428.0,...,390213.0,394921.0,400663.0,405699.0,408596.0,411208.0,414526.0,417568.0,420270.0,421782.0
3,33889,592,Schaumburg,206420.0,206899.0,207706.0,208993.0,210318.0,211430.0,213118.0,...,318749.0,322037.0,325884.0,329969.0,332546.0,335233.0,338328.0,341091.0,343829.0,345585.0
4,18025,629,Evanston,302592.0,302905.0,303645.0,304993.0,306863.0,308430.0,310211.0,...,502345.0,509733.0,518375.0,526181.0,532433.0,538210.0,544713.0,550440.0,554475.0,556319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,31795,21144,Golf,511254.0,512519.0,515788.0,520828.0,524009.0,527693.0,529683.0,...,812506.0,837445.0,865139.0,879458.0,890257.0,898739.0,909127.0,919617.0,929894.0,935990.0
116,32054,21258,Hodgkins,146250.0,144877.0,145472.0,146342.0,148481.0,149861.0,150805.0,...,289536.0,292275.0,296267.0,299403.0,302809.0,304813.0,307362.0,308740.0,310763.0,311582.0
117,53214,21606,McCook,164992.0,162667.0,162618.0,162454.0,162897.0,163778.0,164053.0,...,279015.0,282892.0,288192.0,293391.0,297558.0,301130.0,304551.0,307136.0,309673.0,310853.0
118,31594,22198,Forestview,164312.0,163407.0,165091.0,166567.0,168339.0,169407.0,170902.0,...,236070.0,240865.0,245925.0,249961.0,252382.0,254337.0,256295.0,259127.0,261888.0,264583.0
119,11693,30967,Great Lakes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,177033.0,183722.0,190429.0,194787.0,197091.0,190167.0,181762.0,175064.0,176039.0,179851.0

In [12]:
id_rank_info = cook[['RegionID', "SizeRank", "RegionName"]]
dataset = cook.drop(columns=['RegionID', "SizeRank", "RegionName"], axis = 1)

In [13]:
id_rank_info.to_csv('id_size_region.csv')
dataset.to_csv('dataset.csv')

In [14]:
#inverted sizerank to represent actual weight of digit

In [15]:
plot = np.invert(cook['SizeRank'])

In [16]:
cook['SizeRank'] = plot

In [17]:
cook

,RegionID,SizeRank,RegionName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
0,17426,-4,Chicago,165282.0,165621.0,166381.0,167702.0,169196.0,170566.0,172001.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
1,44597,-533,Cicero,128972.0,129220.0,129706.0,130518.0,131517.0,132603.0,133856.0,...,226907.0,229498.0,232578.0,235283.0,237289.0,238760.0,240861.0,243257.0,245957.0,247645.0
2,50764,-578,Arlington Heights,261429.0,261759.0,262735.0,264406.0,266390.0,267808.0,269428.0,...,390213.0,394921.0,400663.0,405699.0,408596.0,411208.0,414526.0,417568.0,420270.0,421782.0
3,33889,-593,Schaumburg,206420.0,206899.0,207706.0,208993.0,210318.0,211430.0,213118.0,...,318749.0,322037.0,325884.0,329969.0,332546.0,335233.0,338328.0,341091.0,343829.0,345585.0
4,18025,-630,Evanston,302592.0,302905.0,303645.0,304993.0,306863.0,308430.0,310211.0,...,502345.0,509733.0,518375.0,526181.0,532433.0,538210.0,544713.0,550440.0,554475.0,556319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,31795,-21145,Golf,511254.0,512519.0,515788.0,520828.0,524009.0,527693.0,529683.0,...,812506.0,837445.0,865139.0,879458.0,890257.0,898739.0,909127.0,919617.0,929894.0,935990.0
116,32054,-21259,Hodgkins,146250.0,144877.0,145472.0,146342.0,148481.0,149861.0,150805.0,...,289536.0,292275.0,296267.0,299403.0,302809.0,304813.0,307362.0,308740.0,310763.0,311582.0
117,53214,-21607,McCook,164992.0,162667.0,162618.0,162454.0,162897.0,163778.0,164053.0,...,279015.0,282892.0,288192.0,293391.0,297558.0,301130.0,304551.0,307136.0,309673.0,310853.0
118,31594,-22199,Forestview,164312.0,163407.0,165091.0,166567.0,168339.0,169407.0,170902.0,...,236070.0,240865.0,245925.0,249961.0,252382.0,254337.0,256295.0,259127.0,261888.0,264583.0
119,11693,-30968,Great Lakes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,177033.0,183722.0,190429.0,194787.0,197091.0,190167.0,181762.0,175064.0,176039.0,179851.0

In [18]:
cook.to_csv('cookcounty.csv')

In [19]:
cook = cook.drop(['RegionID','SizeRank'],axis=1)

In [20]:
cook = cook.set_index('RegionName')

In [21]:
cook.transpose()

RegionName,Chicago,Cicero,Arlington Heights,Schaumburg,Evanston,Orland Park,Palatine,Des Plaines,Skokie,Oak Lawn,...,Kenilworth,Bedford Park,East Hazel Crest,Phoenix,Merrionette Park,Golf,Hodgkins,McCook,Forestview,Great Lakes
2000-01-31,165282.0,128972.0,261429.0,206420.0,302592.0,241080.0,235324.0,195088.0,239853.0,164582.0,...,916906.0,129734.0,118766.0,71375.0,137084.0,511254.0,146250.0,164992.0,164312.0,NaN
2000-02-29,165621.0,129220.0,261759.0,206899.0,302905.0,241595.0,235879.0,195468.0,240143.0,164751.0,...,920207.0,130722.0,118536.0,71113.0,137635.0,512519.0,144877.0,162667.0,163407.0,NaN
2000-03-31,166381.0,129706.0,262735.0,207706.0,303645.0,242463.0,236957.0,196411.0,240978.0,165133.0,...,923508.0,131705.0,118846.0,71177.0,137944.0,515788.0,145472.0,162618.0,165091.0,NaN
2000-04-30,167702.0,130518.0,264406.0,208993.0,304993.0,243992.0,238737.0,197934.0,242524.0,165835.0,...,933200.0,133287.0,119151.0,71259.0,138793.0,520828.0,146342.0,162454.0,166567.0,NaN
2000-05-31,169196.0,131517.0,266390.0,210318.0,306863.0,245510.0,240503.0,199537.0,244546.0,166470.0,...,943445.0,134495.0,119125.0,70928.0,139376.0,524009.0,148481.0,162897.0,168339.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-31,291647.0,238760.0,411208.0,335233.0,538210.0,364067.0,351596.0,320336.0,380049.0,269409.0,...,1488263.0,241740.0,144221.0,85219.0,184276.0,898739.0,304813.0,301130.0,254337.0,190167.0
2021-11-30,294440.0,240861.0,414526.0,338328.0,544713.0,367834.0,354691.0,323337.0,382814.0,272676.0,...,1501962.0,244923.0,145440.0,87406.0,186584.0,909127.0,307362.0,304551.0,256295.0,181762.0
2021-12-31,297088.0,243257.0,417568.0,341091.0,550440.0,371577.0,357374.0,326300.0,385893.0,275743.0,...,1512967.0,248236.0,147061.0,89012.0,188240.0,919617.0,308740.0,307136.0,259127.0,175064.0
2022-01-31,299729.0,245957.0,420270.0,343829.0,554475.0,374726.0,359804.0,328851.0,389127.0,278739.0,...,1522476.0,251014.0,148995.0,89909.0,190385.0,929894.0,310763.0,309673.0,261888.0,176039.0
2022-02-28,301283.0,247645.0,421782.0,345585.0,556319.0,377024.0,361232.0,330489.0,391447.0,281143.0,...,1524629.0,252952.0,151562.0,92012.0,192366.0,935990.0,311582.0,310853.0,264583.0,179851.0

In [22]:
cook.to_csv('transposed.csv')

In [23]:
cook.reset_index()

,RegionName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
0,Chicago,165282.0,165621.0,166381.0,167702.0,169196.0,170566.0,172001.0,173594.0,175129.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
1,Cicero,128972.0,129220.0,129706.0,130518.0,131517.0,132603.0,133856.0,135013.0,136012.0,...,226907.0,229498.0,232578.0,235283.0,237289.0,238760.0,240861.0,243257.0,245957.0,247645.0
2,Arlington Heights,261429.0,261759.0,262735.0,264406.0,266390.0,267808.0,269428.0,271458.0,273819.0,...,390213.0,394921.0,400663.0,405699.0,408596.0,411208.0,414526.0,417568.0,420270.0,421782.0
3,Schaumburg,206420.0,206899.0,207706.0,208993.0,210318.0,211430.0,213118.0,215316.0,217632.0,...,318749.0,322037.0,325884.0,329969.0,332546.0,335233.0,338328.0,341091.0,343829.0,345585.0
4,Evanston,302592.0,302905.0,303645.0,304993.0,306863.0,308430.0,310211.0,312727.0,316042.0,...,502345.0,509733.0,518375.0,526181.0,532433.0,538210.0,544713.0,550440.0,554475.0,556319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Golf,511254.0,512519.0,515788.0,520828.0,524009.0,527693.0,529683.0,535512.0,537426.0,...,812506.0,837445.0,865139.0,879458.0,890257.0,898739.0,909127.0,919617.0,929894.0,935990.0
116,Hodgkins,146250.0,144877.0,145472.0,146342.0,148481.0,149861.0,150805.0,151201.0,152082.0,...,289536.0,292275.0,296267.0,299403.0,302809.0,304813.0,307362.0,308740.0,310763.0,311582.0
117,McCook,164992.0,162667.0,162618.0,162454.0,162897.0,163778.0,164053.0,165607.0,166947.0,...,279015.0,282892.0,288192.0,293391.0,297558.0,301130.0,304551.0,307136.0,309673.0,310853.0
118,Forestview,164312.0,163407.0,165091.0,166567.0,168339.0,169407.0,170902.0,172877.0,173073.0,...,236070.0,240865.0,245925.0,249961.0,252382.0,254337.0,256295.0,259127.0,261888.0,264583.0
119,Great Lakes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,177033.0,183722.0,190429.0,194787.0,197091.0,190167.0,181762.0,175064.0,176039.0,179851.0

In [27]:
cook.to_csv('cookcounty.csv')

In [28]:
cook

,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,...,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28
RegionName,,,,,,,,,,,,,,,,,,,,,
Chicago,165282.0,165621.0,166381.0,167702.0,169196.0,170566.0,172001.0,173594.0,175129.0,176760.0,...,278732.0,281106.0,283652.0,287049.0,289393.0,291647.0,294440.0,297088.0,299729.0,301283.0
Cicero,128972.0,129220.0,129706.0,130518.0,131517.0,132603.0,133856.0,135013.0,136012.0,137035.0,...,226907.0,229498.0,232578.0,235283.0,237289.0,238760.0,240861.0,243257.0,245957.0,247645.0
Arlington Heights,261429.0,261759.0,262735.0,264406.0,266390.0,267808.0,269428.0,271458.0,273819.0,276055.0,...,390213.0,394921.0,400663.0,405699.0,408596.0,411208.0,414526.0,417568.0,420270.0,421782.0
Schaumburg,206420.0,206899.0,207706.0,208993.0,210318.0,211430.0,213118.0,215316.0,217632.0,219828.0,...,318749.0,322037.0,325884.0,329969.0,332546.0,335233.0,338328.0,341091.0,343829.0,345585.0
Evanston,302592.0,302905.0,303645.0,304993.0,306863.0,308430.0,310211.0,312727.0,316042.0,320664.0,...,502345.0,509733.0,518375.0,526181.0,532433.0,538210.0,544713.0,550440.0,554475.0,556319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Golf,511254.0,512519.0,515788.0,520828.0,524009.0,527693.0,529683.0,535512.0,537426.0,545143.0,...,812506.0,837445.0,865139.0,879458.0,890257.0,898739.0,909127.0,919617.0,929894.0,935990.0
Hodgkins,146250.0,144877.0,145472.0,146342.0,148481.0,149861.0,150805.0,151201.0,152082.0,153320.0,...,289536.0,292275.0,296267.0,299403.0,302809.0,304813.0,307362.0,308740.0,310763.0,311582.0
McCook,164992.0,162667.0,162618.0,162454.0,162897.0,163778.0,164053.0,165607.0,166947.0,168724.0,...,279015.0,282892.0,288192.0,293391.0,297558.0,301130.0,304551.0,307136.0,309673.0,310853.0
Forestview,164312.0,163407.0,165091.0,166567.0,168339.0,169407.0,170902.0,172877.0,173073.0,173201.0,...,236070.0,240865.0,245925.0,249961.0,252382.0,254337.0,256295.0,259127.0,261888.0,264583.0
Great Lakes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,177033.0,183722.0,190429.0,194787.0,197091.0,190167.0,181762.0,175064.0,176039.0,179851.0