In [2]:
import pycaret

In [30]:
import matplotlib.pyplot as plt 
from matplotlib.pylab import rcParams
import pandas as pd
import scipy.stats as sts
import numpy as np
%matplotlib inline
import seaborn as sns
sns.set(style='darkgrid',font='Arial',font_scale=1.2)
rcParams['figure.figsize'] = 12,8
rcParams['axes.spines.top'] = False
rcParams['axes.spines.right'] = False

In [31]:
dataset = pd.read_csv('cookcounty.csv')

In [32]:
dataset = dataset.set_index('RegionName')

In [33]:
dataset = dataset.T

In [34]:
dataset

RegionName,Chicago,Cicero,Arlington Heights,Schaumburg,Evanston,Orland Park,Palatine,Des Plaines,Skokie,Oak Lawn,...,Kenilworth,Bedford Park,East Hazel Crest,Phoenix,Merrionette Park,Golf,Hodgkins,McCook,Forestview,Great Lakes
2000-01-31,165282.0,128972.0,261429.0,206420.0,302592.0,241080.0,235324.0,195088.0,239853.0,164582.0,...,916906.0,129734.0,118766.0,71375.0,137084.0,511254.0,146250.0,164992.0,164312.0,NaN
2000-02-29,165621.0,129220.0,261759.0,206899.0,302905.0,241595.0,235879.0,195468.0,240143.0,164751.0,...,920207.0,130722.0,118536.0,71113.0,137635.0,512519.0,144877.0,162667.0,163407.0,NaN
2000-03-31,166381.0,129706.0,262735.0,207706.0,303645.0,242463.0,236957.0,196411.0,240978.0,165133.0,...,923508.0,131705.0,118846.0,71177.0,137944.0,515788.0,145472.0,162618.0,165091.0,NaN
2000-04-30,167702.0,130518.0,264406.0,208993.0,304993.0,243992.0,238737.0,197934.0,242524.0,165835.0,...,933200.0,133287.0,119151.0,71259.0,138793.0,520828.0,146342.0,162454.0,166567.0,NaN
2000-05-31,169196.0,131517.0,266390.0,210318.0,306863.0,245510.0,240503.0,199537.0,244546.0,166470.0,...,943445.0,134495.0,119125.0,70928.0,139376.0,524009.0,148481.0,162897.0,168339.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-31,291647.0,238760.0,411208.0,335233.0,538210.0,364067.0,351596.0,320336.0,380049.0,269409.0,...,1488263.0,241740.0,144221.0,85219.0,184276.0,898739.0,304813.0,301130.0,254337.0,190167.0
2021-11-30,294440.0,240861.0,414526.0,338328.0,544713.0,367834.0,354691.0,323337.0,382814.0,272676.0,...,1501962.0,244923.0,145440.0,87406.0,186584.0,909127.0,307362.0,304551.0,256295.0,181762.0
2021-12-31,297088.0,243257.0,417568.0,341091.0,550440.0,371577.0,357374.0,326300.0,385893.0,275743.0,...,1512967.0,248236.0,147061.0,89012.0,188240.0,919617.0,308740.0,307136.0,259127.0,175064.0
2022-01-31,299729.0,245957.0,420270.0,343829.0,554475.0,374726.0,359804.0,328851.0,389127.0,278739.0,...,1522476.0,251014.0,148995.0,89909.0,190385.0,929894.0,310763.0,309673.0,261888.0,176039.0
2022-02-28,301283.0,247645.0,421782.0,345585.0,556319.0,377024.0,361232.0,330489.0,391447.0,281143.0,...,1524629.0,252952.0,151562.0,92012.0,192366.0,935990.0,311582.0,310853.0,264583.0,179851.0

In [42]:
chicago = dataset['Chicago']

In [43]:
chicago

2000-01-31    165282.0
2000-02-29    165621.0
2000-03-31    166381.0
2000-04-30    167702.0
2000-05-31    169196.0
                ...
2021-10-31    291647.0
2021-11-30    294440.0
2021-12-31    297088.0
2022-01-31    299729.0
2022-02-28    301283.0
Name: Chicago, Length: 266, dtype: float64

In [36]:
# load dataset
# init setup
pip install pycaret-ts-alpha

SyntaxError: invalid syntax (39525545.py, line 3)

In [45]:
from pycaret.time_series import *
exp_name = setup(data = dataset,  fh = 12)

ModuleNotFoundError: No module named 'pycaret.utils.time_series'; 'pycaret.utils' is not a package

In [39]:
airline

Period
1949-01    112.0
1949-02    118.0
1949-03    132.0
1949-04    129.0
1949-05    121.0
           ...
1960-08    606.0
1960-09    508.0
1960-10    461.0
1960-11    390.0
1960-12    432.0
Freq: M, Name: Number of airline passengers, Length: 144, dtype: float64

<bound method IndexOpsMixin.value_counts of Period
1949-01    112.0
1949-02    118.0
1949-03    132.0
1949-04    129.0
1949-05    121.0
           ...
1960-08    606.0
1960-09    508.0
1960-10    461.0
1960-11    390.0
1960-12    432.0
Freq: M, Name: Number of airline passengers, Length: 144, dtype: float64>